# Generated by Django 5.0.6 on 2024-05-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='banner_image',
            field=models.ImageField(default='no_photo.jpg', upload_to='game_banners/'),
        ),
    ]
