# Generated by Django 5.0.6 on 2024-05-24 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_game_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_image', models.ImageField(upload_to='carousel/')),
                ('caption', models.CharField(max_length=100)),
                ('small_image2', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('small_image3', models.ImageField(blank=True, null=True, upload_to='carousel/')),
                ('game1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousel_game1', to='store.game')),
                ('game2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_game2', to='store.game')),
                ('game3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carousel_game3', to='store.game')),
            ],
        ),
    ]
