# Generated by Django 5.0.6 on 2024-06-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_gamepass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AlterField(
            model_name='gamepass',
            name='image',
            field=models.ImageField(upload_to='gamepass_images/'),
        ),
    ]
