# Generated by Django 5.0.3 on 2024-04-29 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_feedback_update_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
