# Generated by Django 5.0.3 on 2024-04-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_cinema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='film_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
